//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Content", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BANK NAME.
        /// </summary>
        internal static string bank_name {
            get {
                return ResourceManager.GetString("bank_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.O.T Dormitories&apos; Fees (PDF).
        /// </summary>
        internal static string btn_bot_dormitofies_fees {
            get {
                return ResourceManager.GetString("btn_bot_dormitofies_fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.O.T Dormitories&apos; Fees  (2018 Spring) (PDF).
        /// </summary>
        internal static string btn_bot_dormitories_fees_2018 {
            get {
                return ResourceManager.GetString("btn_bot_dormitories_fees_2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        internal static string btn_clear_filter {
            get {
                return ResourceManager.GetString("btn_clear_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMU Dormitories&apos; Fees (PDF).
        /// </summary>
        internal static string btn_emu_dormitories_fees {
            get {
                return ResourceManager.GetString("btn_emu_dormitories_fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btn_search {
            get {
                return ResourceManager.GetString("btn_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMU B.O.T Dormitories.
        /// </summary>
        internal static string emu_bot_dormitories {
            get {
                return ResourceManager.GetString("emu_bot_dormitories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fees are per person, in U.S. Dollars, and to be paid.
        /// </summary>
        internal static string emu_bot_dormitories1 {
            get {
                return ResourceManager.GetString("emu_bot_dormitories1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on an annual basis..
        /// </summary>
        internal static string emu_bot_dormitories2 {
            get {
                return ResourceManager.GetString("emu_bot_dormitories2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cash payment or the payment of the I. Installment has to be made on the registration date..
        /// </summary>
        internal static string emu_bot_dormitories3 {
            get {
                return ResourceManager.GetString("emu_bot_dormitories3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fees can be paid cash or in installments..
        /// </summary>
        internal static string emu_bot_dormitories4 {
            get {
                return ResourceManager.GetString("emu_bot_dormitories4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the dormitories request deposit..
        /// </summary>
        internal static string emu_bot_dormitories5 {
            get {
                return ResourceManager.GetString("emu_bot_dormitories5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dormitory fees include electricity (*), water, cleaning, and other similar expenses.
        /// </summary>
        internal static string emu_bot_dormitories6 {
            get {
                return ResourceManager.GetString("emu_bot_dormitories6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*) Some of the dormitories has electric quota..
        /// </summary>
        internal static string emu_bot_dormitories7 {
            get {
                return ResourceManager.GetString("emu_bot_dormitories7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All dormitories have rooms for male and female students..
        /// </summary>
        internal static string emu_bot_dormitories8 {
            get {
                return ResourceManager.GetString("emu_bot_dormitories8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMU Dormitories Bank Accounts.
        /// </summary>
        internal static string emu_dormitories_bank_accounts {
            get {
                return ResourceManager.GetString("emu_dormitories_bank_accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMU Dormitories&apos; Fees (PDF).
        /// </summary>
        internal static string emu_dormitories_fees_pdf {
            get {
                return ResourceManager.GetString("emu_dormitories_fees_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastern Mediterranean University has the best dormitories in the region, Enjoy the slideshow before you begin your search..
        /// </summary>
        internal static string emu_intro_text {
            get {
                return ResourceManager.GetString("emu_intro_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privately-Owned Campus Dormitories.
        /// </summary>
        internal static string filter_dormitory_type_bot_dormitories {
            get {
                return ResourceManager.GetString("filter_dormitory_type_bot_dormitories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMU Dormitories.
        /// </summary>
        internal static string filter_dormitory_type_emu_dormitories {
            get {
                return ResourceManager.GetString("filter_dormitory_type_emu_dormitories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Range.
        /// </summary>
        internal static string filter_glide_price_range {
            get {
                return ResourceManager.GetString("filter_glide_price_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed.
        /// </summary>
        internal static string filter_header_bed {
            get {
                return ResourceManager.GetString("filter_header_bed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchenette.
        /// </summary>
        internal static string filter_header_kitchenette {
            get {
                return ResourceManager.GetString("filter_header_kitchenette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide options.
        /// </summary>
        internal static string filter_header_more_options {
            get {
                return ResourceManager.GetString("filter_header_more_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nececities.
        /// </summary>
        internal static string filter_header_nececities {
            get {
                return ResourceManager.GetString("filter_header_nececities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other options.
        /// </summary>
        internal static string filter_header_other_options {
            get {
                return ResourceManager.GetString("filter_header_other_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WC-Shower.
        /// </summary>
        internal static string filter_header_wc_shower {
            get {
                return ResourceManager.GetString("filter_header_wc_shower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        internal static string filter_head_internet {
            get {
                return ResourceManager.GetString("filter_head_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        internal static string filter_head_tv {
            get {
                return ResourceManager.GetString("filter_head_tv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air condition (AC).
        /// </summary>
        internal static string filter_option_air_condition {
            get {
                return ResourceManager.GetString("filter_option_air_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bunk.
        /// </summary>
        internal static string filter_option_bed_bunk {
            get {
                return ResourceManager.GetString("filter_option_bed_bunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string filter_option_bed_normal {
            get {
                return ResourceManager.GetString("filter_option_bed_normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cafeteria.
        /// </summary>
        internal static string filter_option_cafeteria {
            get {
                return ResourceManager.GetString("filter_option_cafeteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Heating/Cooling.
        /// </summary>
        internal static string filter_option_center_heating_cooling {
            get {
                return ResourceManager.GetString("filter_option_center_heating_cooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator.
        /// </summary>
        internal static string filter_option_generator {
            get {
                return ResourceManager.GetString("filter_option_generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless.
        /// </summary>
        internal static string filter_option_internet_wireless {
            get {
                return ResourceManager.GetString("filter_option_internet_wireless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable.
        /// </summary>
        internal static string filter_option_internt_cable {
            get {
                return ResourceManager.GetString("filter_option_internt_cable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flats.
        /// </summary>
        internal static string filter_option_kitchenette_flats {
            get {
                return ResourceManager.GetString("filter_option_kitchenette_flats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Room.
        /// </summary>
        internal static string filter_option_kitchenette_room {
            get {
                return ResourceManager.GetString("filter_option_kitchenette_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laundry.
        /// </summary>
        internal static string filter_option_laundry {
            get {
                return ResourceManager.GetString("filter_option_laundry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrigerator.
        /// </summary>
        internal static string filter_option_refrigerator {
            get {
                return ResourceManager.GetString("filter_option_refrigerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Tel..
        /// </summary>
        internal static string filter_option_room_tel {
            get {
                return ResourceManager.GetString("filter_option_room_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Hall.
        /// </summary>
        internal static string filter_option_tv_hall {
            get {
                return ResourceManager.GetString("filter_option_tv_hall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Room.
        /// </summary>
        internal static string filter_option_tv_room {
            get {
                return ResourceManager.GetString("filter_option_tv_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string filter_option_wc_shower_common {
            get {
                return ResourceManager.GetString("filter_option_wc_shower_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flats.
        /// </summary>
        internal static string filter_option_wc_shower_flats {
            get {
                return ResourceManager.GetString("filter_option_wc_shower_flats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Room.
        /// </summary>
        internal static string filter_option_wc_shower_room {
            get {
                return ResourceManager.GetString("filter_option_wc_shower_room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 m2  to  20 m2.
        /// </summary>
        internal static string filter_range_10_to_20 {
            get {
                return ResourceManager.GetString("filter_range_10_to_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21 m2  to  25 m2.
        /// </summary>
        internal static string filter_range_21_to_25 {
            get {
                return ResourceManager.GetString("filter_range_21_to_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26 m2  to  30 m2.
        /// </summary>
        internal static string filter_range_26_to_30 {
            get {
                return ResourceManager.GetString("filter_range_26_to_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than 30 m2.
        /// </summary>
        internal static string filter_range_greater_than_30 {
            get {
                return ResourceManager.GetString("filter_range_greater_than_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dormitory Name.
        /// </summary>
        internal static string filter_select_dormitory_name {
            get {
                return ResourceManager.GetString("filter_select_dormitory_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dormitory type.
        /// </summary>
        internal static string filter_select_dormitory_type {
            get {
                return ResourceManager.GetString("filter_select_dormitory_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Area.
        /// </summary>
        internal static string filter_select_room_area {
            get {
                return ResourceManager.GetString("filter_select_room_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN TL.
        /// </summary>
        internal static string iban_tl {
            get {
                return ResourceManager.GetString("iban_tl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN USD.
        /// </summary>
        internal static string iban_usd {
            get {
                return ResourceManager.GetString("iban_usd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment: 25 March 2019.
        /// </summary>
        internal static string installment_date_2019 {
            get {
                return ResourceManager.GetString("installment_date_2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment: 25 April 2019.
        /// </summary>
        internal static string installment_date_april_2019 {
            get {
                return ResourceManager.GetString("installment_date_april_2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment: 25 December 2018.
        /// </summary>
        internal static string installment_date_december_2018 {
            get {
                return ResourceManager.GetString("installment_date_december_2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment: 27 May 2019.
        /// </summary>
        internal static string Installment_date_may_2019 {
            get {
                return ResourceManager.GetString("Installment_date_may_2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment: 26  November 2018.
        /// </summary>
        internal static string installment_date_november_2019 {
            get {
                return ResourceManager.GetString("installment_date_november_2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select any checkbox filter to begin.
        /// </summary>
        internal static string instruction_text {
            get {
                return ResourceManager.GetString("instruction_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string language_id {
            get {
                return ResourceManager.GetString("language_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        internal static string lang_code {
            get {
                return ResourceManager.GetString("lang_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /FeesAndFacilities/Index/tr.
        /// </summary>
        internal static string lang_trans_link {
            get {
                return ResourceManager.GetString("lang_trans_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elektric (*), water, internet and cleaning services are included in the fee..
        /// </summary>
        internal static string ories_2 {
            get {
                return ResourceManager.GetString("ories_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*) Electric has quota. If the quota exceeded, students can buy electric for their rooms..
        /// </summary>
        internal static string ories_3 {
            get {
                return ResourceManager.GetString("ories_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall Semester.
        /// </summary>
        internal static string ories_fall_semester {
            get {
                return ResourceManager.GetString("ories_fall_semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment: During Registration.
        /// </summary>
        internal static string ories_installment_during_registration {
            get {
                return ResourceManager.GetString("ories_installment_during_registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment: 25 October 2018.
        /// </summary>
        internal static string ories_installment_october {
            get {
                return ResourceManager.GetString("ories_installment_october", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring Semester.
        /// </summary>
        internal static string ories_spring_semester {
            get {
                return ResourceManager.GetString("ories_spring_semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Dormitories in the Campus.
        /// </summary>
        internal static string private_dormitories_in_the_campus {
            get {
                return ResourceManager.GetString("private_dormitories_in_the_campus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamacıoğlu Dormitory.
        /// </summary>
        internal static string private_dormitory_in_campus_link {
            get {
                return ResourceManager.GetString("private_dormitory_in_campus_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMU Dormitories.
        /// </summary>
        internal static string static_text_emu_dormitories {
            get {
                return ResourceManager.GetString("static_text_emu_dormitories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fees are in Turkish Lira (TL ) and for one semester.
        /// </summary>
        internal static string static_text_emu_dormitories0 {
            get {
                return ResourceManager.GetString("static_text_emu_dormitories0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees can be paid either cash or in 4 installments..
        /// </summary>
        internal static string static_text_emu_dormitories_1 {
            get {
                return ResourceManager.GetString("static_text_emu_dormitories_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees and Facilities.
        /// </summary>
        internal static string static_text_fees_and_facilities {
            get {
                return ResourceManager.GetString("static_text_fees_and_facilities", resourceCulture);
            }
        }
    }
}
